<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Booking;

class DataSDGSeeder2 extends Seeder
{
    public function run(): void
    {
        $data = [
            // juli
            'MCC-2406-CUIN' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2406-TORB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2406-WGXT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2406-JOKI' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2406-IHXZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-Q0Z5' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2406-DPSA' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-LHZ7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-FMV3' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-8VAA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2406-10QF' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-9ILM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-PW22' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-PRVN' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2406-BT85' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-NIO7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-ZP0J' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-QL8J' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-GQBS' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-F4Q3' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2405-O39P' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-XN4H' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-J8TQ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-XD8G' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-CNIO' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-SHA5' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2407-4GML' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2406-IHXZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-QQRX' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-CNO6' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",

            'MCC-2406-U0UL' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-L8Z7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-HHBD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-M17F' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-ETAR' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-HUGP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-YLIJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-DLRD' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-DN6F' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2406-H9OJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\".\"]]",
            
            // Agustus
            'MCC-2407-0891' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-H7EZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-OED6' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2407-6QTF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-0QHM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-1LXR' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-43QV' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2407-LEC4' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2407-RILT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-USCA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",

            'MCC-2407-QCK7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2407-IUQK' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-7OKB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-TEL9' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-AWVA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2407-T5JT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2407-N1VM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-ERE4' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-W7H4' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-JAB3' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",

            'MCC-2408-NOAS' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-7NQC' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-KPDS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2408-QHLI' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-YU5P' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2407-DYXG' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-KN9F' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2407-WWDA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-AWE7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2407-XGV2' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            // September
            'MCC-2408-GAV8' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-JGQA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-EUJE' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-XDNA' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-0RKJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-QRXV' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-5JAF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-RXQA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-K2KM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2408-14MX' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",

            'MCC-2408-3XOD' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2408-WKY8' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2408-FNJK' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-BRID' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2408-YQVJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2408-G5BM' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2408-ECDI' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-7DVA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2408-WPIF' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-EIXF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",

            'MCC-2408-J8TG' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2408-DQJ5' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2408-ZOAT' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2408-2RAQ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-NRI2' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2408-SVN8' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2408-TKSU' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-Y3Y9' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2407-LAVP' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2407-AGXT' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",

            // Oktober
            'MCC-2409-UV8X' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-GZ11' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-KRGG' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-6NUF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2409-D5HS' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-FOMW' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-C4V1' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-WKER' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-YAK6' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-TBJD' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",

            'MCC-2409-UV2L' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2409-4A0M' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-TKN2' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-XOFW' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-YA90' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2409-2DQU' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-PEYC' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2409-E84U' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2409-ABNP' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG9\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-DGQQ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2409-IHF0' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-AKFT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-35GK' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-K54E' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-CT7O' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-MARZ' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2409-30GX' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2409-WYMP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2409-0YZQ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2408-8VNF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",

            // November
            'MCC-2410-Q1PU' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-PCLM' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2410-ICUX' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-SIJV' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2410-51MY' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-HAAE' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-YIAR' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2410-KKT8' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2410-TF5C' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-7FGL' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2410-BHMX' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-JSAA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-HDTP' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-IFJF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-WROV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-D1DJ' => "[[\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2410-MHTI' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-CKHK' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-W8I1' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2410-PNSV' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",

            'MCC-2410-NRQH' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-APPM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG9\",\".\"]]",
            'MCC-2410-FQUZ' => "[[\"SDG8\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG9\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-KCF7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-MV19' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-NA8S' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2410-58XN' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-EWG3' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-TVNL' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-JT6J' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG9\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            // Desember
            'MCC-2411-EUWM' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-2PVD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2411-NNLG' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2411-4RGF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2411-BHO7' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2411-YCPA' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-WWWW' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2411-KYON' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2411-SBTX' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2411-YE5T' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            
            'MCC-2411-DJOA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-4NFP' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2411-DMYD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2411-W7OG' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-SLEP' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-LMYD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2411-KWLQ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2411-XUBW' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-RSQY' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2411-AXMA' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",

            'MCC-2411-IU6F' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-FZJ5' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-N8UA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2411-SH2D' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2411-DJQT' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2410-AIAH' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2410-XLRD' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-2PNU' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2410-KC4I' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2410-FR90' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

        ];

        foreach ($data as $kode => $sdgs) {
            Booking::where('kode_booking', $kode)
                ->update(['sdgs_data' => json_encode($sdgs)]);
        }
    }
}

   /*id_sdgs	deskripsi
SDG01	MMenghapuskan kemiskinan dalam segala bentuk dan memastikan semua orang memiliki akses ke kebutuhan dasar seperti makanan, tempat tinggal, dan pekerjaan yang layak.
SDG02	Memastikan semua orang memiliki akses ke makanan bergizi dan mengembangkan sistem pangan yang berkelanjutan.
SDG03	Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.
SDG04	Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.
SDG05	Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.
SDG07	Menggunakan sumber energi yang ramah lingkungan dan dapat diperoleh dengan harga yang terjangkau.
SDG08	Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.
SDG09	Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.
SDG10	Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.
SDG12	Menggunakan sumber daya secara bijak dan mengurangi limbah.
SDG16	Membangun masyarakat yang damai, adil, dan transparan.
SDG17	Bekerja sama untuk mencapai semua tujuan SDGs.

            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
            '' => "[[\"SDG0\",\".\"], [\"SDG0\",\".\"], [\"SDG0\",\".\"]]",
*/