<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Booking;

class DataSDGSeeder1 extends Seeder
{
    public function run(): void
    {
        $data = [
            // Periode Januari - Juni 2024

            // Januari
            'MCC-2401-JFSG' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2401-XAOD' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-VTHL' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-QYGJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-EVIX' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-XNPS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-BGQM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-GS3Y' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2401-BOBF' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2401-WZXV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
        
            'MCC-2401-7PGY' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2401-KJKZ' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-WFVJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-GZLA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-IVW1' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-YNH2' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-E4WW' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-HNQL' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-8OL2' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-B4QB' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2401-KM1N' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-CSBU' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-BG1K' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-974L' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-HMZU' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-GDPJ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-VTHL' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2401-PV2M' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-W4LN' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2401-H1AI' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2401-H0EW' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-A34X' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-HKXX' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-AKXD' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2401-VA3K' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-UAQN' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-AFKD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-G87N' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-BDGZ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-FCNR' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
        
            'MCC-2401-INEH' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-TXO7' => "[[\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-P7RA' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-AKXD' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2401-KJKZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-QHML' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-YBBE' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-39ZV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2401-XLXH' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-HGXB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
                    

            // Februari
            'MCC-2401-CDS6' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-ZSGV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-WBHH' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-DYMS' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-MYSR' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-QPOW' => "[[\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-CP6U' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-LDJD' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-ZY9P' => "[[\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-0XMT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2401-CUTT' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG11\",\"desc\"]]",
            'MCC-2401-5L2X' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-NHIL' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-PXCC' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-V5ZB' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2401-JILJ' => "[[\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2401-NJFP' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2402-YNKT' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2401-E9VS' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-0CPL' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",

            'MCC-2401-I2OS' => "[[\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2401-WBNT' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2402-IZVQ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2402-83AO' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-MYSR' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2402-BXRL' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-I2Y6' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2402-9QAE' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2401-XLR6' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG05\",\"Memberikan hak yang sama bagi laki-laki dan perempuan dalam semua aspek kehidupan, termasuk pekerjaan dan pendidikan.\"]]",
            'MCC-2401-DDPB' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",

        

            // Maret 
            'MCC-2402-7EAG' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2402-0X2I' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2402-UJOY' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2402-ECQP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2402-VP0M' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2402-UR00' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-1V9P' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG11\",\"desc\"]]",
            'MCC-2402-2VMC' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2403-QU1B' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2402-L876' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",

            'MCC-2402-CXHG' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2402-JGJG' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2402-MT4O' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2402-AWKN' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2402-KVIV' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-I2OS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2401-1V9P' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2401-XO9J' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2403-B6TP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2402-VIDM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            
            'MCC-2402-D4KH' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2402-VU7D' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2403-W2IR' => "[[\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2403-TIJ9' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2403-GIGF' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2402-BXRL' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2403-4TFZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2403-VN9O' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2402-K1VC' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-F8GM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",


            // April
            'MCC-2403-HBAB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2403-RCJE' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-ACTB' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG11\",\"Membangun kota dan komunitas yang inklusif, aman, dan berkelanjutan.\"]]",
            'MCC-2403-1LPY' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2403-UZ4A' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-OBOY' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-X6FV' => "[[\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-YNWU' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2403-RWAO' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2404-BAS9' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",

            'MCC-2404-UMGV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2403-WXEY' => "[[\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2404-ITMV' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"]]",
            'MCC-2403-1LPY' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2404-QKGK' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"]]",
            'MCC-2403-QNDU' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2403-GLMJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2404-WYHI' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-9NO4' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2404-IPZ8' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2403-N3JF' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2403-6JWP' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-RYJG' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-PJNS' => "[[\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-WSE8' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2403-JBDB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-BRVR' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-JRQJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2404-FBFS' => "[[\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-FY34' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",


            // Mei
            'MCC-2404-CDHW' => "[[\"SDG05\",\"Mencapai kesetaraan gender dan memberdayakan semua perempuan dan anak perempuan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-DW1R' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2404-H6PU' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2405-EE0Y' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-1JOP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-UQ7M' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-EZXL' => "[[\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2403-YNWU' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2404-LZZB' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-2OCH' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",

            'MCC-2403-3YGS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-V2DD' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-FCWU' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-2XPA' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Membangun infrastruktur yang kuat, industri yang inklusif, dan mendorong inovasi.\"]]",
            'MCC-2405-2BLK' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-FFPD' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-HOR5' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2403-RK1Q' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-DKPW' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-0BQZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",

            'MCC-2405-JJUZ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-RONL' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2404-SXR4' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2403-EIQU' => "[[\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-LIXK' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2405-CVEN' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-HSZK' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2404-JRQJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-0T68' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",


            // Juni
            'MCC-2405-X7KV' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-1PQQ' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-LTX0' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-0YZS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-6ENJ' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-2YG7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-OYRO' => "[[\"SDG17\",\"Menguatkan kemitraan global untuk pembangunan berkelanjutan.\"]]",
            'MCC-2404-17UY' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2405-KBTJ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-X1ZJ' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",

            'MCC-2405-1AIG' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-AXCE' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2405-BIQH' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG10\",\"Mengurangi perbedaan ekonomi dan sosial di antara kelompok masyarakat.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-IHAI' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2404-1JOP' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-IFKW' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-OYGW' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",
            'MCC-2405-4M1M' => "[[\"SDG03\",\"Meningkatkan kesehatan dan kesejahteraan semua orang, termasuk akses ke layanan kesehatan dan gaya hidup sehat.\"], [\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-PDUO' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG12\",\"Menggunakan sumber daya secara bijak dan mengurangi limbah.\"]]",
            'MCC-2406-NNV5' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Membangun infrastruktur yang kuat, industri yang inklusif, dan mendorong inovasi.\"]]",

            'MCC-2406-KNSM' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"]]",
            'MCC-2406-BRFQ' => "[[\"SDG16\",\"Membangun masyarakat yang damai, adil, dan transparan.\"]]",
            'MCC-2406-URJ8' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-4XXH' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2404-QRAS' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-PO3T' => "[[\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"], [\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2406-M50J' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2406-AQF7' => "[[\"SDG04\",\"Memberikan pendidikan yang baik dan merata bagi semua orang agar memiliki keterampilan untuk masa depan.\"], [\"SDG08\",\"Meningkatkan kesempatan kerja yang layak dan membangun ekonomi yang stabil untuk semua orang.\"]]",
            'MCC-2405-KEST' => "[[\"SDG09\",\"Mendorong pembangunan industri dan inovasi yang mendukung ekonomi berkelanjutan.\"]]",
            'MCC-2404-XOOP' => "[[\"SDG17\",\"Bekerja sama untuk mencapai semua tujuan SDGs.\"]]",

        ];

        foreach ($data as $kode => $sdgs) {
            Booking::where('kode_booking', $kode)
                ->update(['sdgs_data' => json_encode($sdgs)]);
        }
    }
}
