<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LantaiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('roomlist')->insert([
            [
                'id' => 1,
                'nama_ruangan' => 'Stage Outdoor',
                'lantai' => 1,
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '12:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-25 02:30:00',
                'updated_at' => '2024-10-25 02:30:00',
            ],
            [
                'id' => 2,
                'nama_ruangan' => 'Teras Tengah',
                'lantai' => 2,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-27 07:00:00',
                'updated_at' => '2024-10-27 07:00:00',
            ],
            [
                'id' => 3,
                'nama_ruangan' => 'Teras Utara',
                'lantai' => 2,
                'waktu_mulai' => '11:00:00',
                'waktu_selesai' => '13:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-28 04:00:00',
                'updated_at' => '2024-10-28 04:00:00',
            ],
            [
                'id' => 4,
                'nama_ruangan' => 'Coworking Space 1',
                'lantai' => 4,
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '17:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-29 01:45:00',
                'updated_at' => '2024-10-29 01:45:00',
            ],
            [
                'id' => 5,
                'nama_ruangan' => 'Studio Musik & Recording',
                'lantai' => 4,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-30 03:00:00',
                'updated_at' => '2024-10-30 03:00:00',
            ],
            [
                'id' => 6,
                'nama_ruangan' => 'Workshop Seni',
                'lantai' => 4,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-25 05:00:00',
                'updated_at' => '2024-10-25 05:00:00',
            ],
            [
                'id' => 7,
                'nama_ruangan' => 'Lab Komputer',
                'lantai' => 4,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-26 03:15:00',
                'updated_at' => '2024-10-26 03:15:00',
            ],
            [
                'id' => 8,
                'nama_ruangan' => 'Open Public Space Utara',
                'lantai' => 4,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-28 08:00:00',
                'updated_at' => '2024-10-28 08:00:00',
            ],
            [
                'id' => 9,
                'nama_ruangan' => 'Coworking Space 1',
                'lantai' => 5,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-25 07:00:00',
                'updated_at' => '2024-10-25 07:00:00',
            ],
            [
                'id' => 10,
                'nama_ruangan' => 'Coworking Space 2',
                'lantai' => 5,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-30 02:00:00',
                'updated_at' => '2024-10-30 02:00:00',
            ],
            [
                'id' => 11,
                'nama_ruangan' => 'Amphitheater 1',
                'lantai' => 5,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-26 04:00:00',
                'updated_at' => '2024-10-26 04:00:00',
            ],
            [
                'id' => 12,
                'nama_ruangan' => 'Amphitheater 2',
                'lantai' => 5,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-29 03:00:00',
                'updated_at' => '2024-10-29 03:00:00',
            ],
            [
                'id' => 13,
                'nama_ruangan' => 'Studio Foto',
                'lantai' => 5,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-31 03:30:00',
                'updated_at' => '2024-10-31 03:30:00',
            ],
            [
                'id' => 14,
                'nama_ruangan' => 'Ruang Fashion',
                'lantai' => 5,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-28 05:30:00',
                'updated_at' => '2024-10-28 05:30:00',
            ],
            [
                'id' => 15,
                'nama_ruangan' => 'Open Public Space Utara',
                'lantai' => 6,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-30 06:00:00',
                'updated_at' => '2024-10-30 06:00:00',
            ],
            [
                'id' => 16,
                'nama_ruangan' => 'Rooftop',
                'lantai' => 8,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-25 09:00:00',
                'updated_at' => '2024-10-25 09:00:00',
            ],
            [
                'id' => 17,
                'nama_ruangan' => 'Teras Selatan',
                'lantai' => 2,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-26 08:30:00',
                'updated_at' => '2024-10-26 08:30:00',
            ],
            [
                'id' => 18,
                'nama_ruangan' => 'Open Public Space Utara',
                'lantai' => 2,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-27 03:00:00',
                'updated_at' => '2024-10-27 03:00:00',
            ],
            [
                'id' => 19,
                'nama_ruangan' => 'Creative City Planning Gallery',
                'lantai' => 2,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-28 02:00:00',
                'updated_at' => '2024-10-28 02:00:00',
            ],
            [
                'id' => 20,
                'nama_ruangan' => 'Ruang Podcast',
                'lantai' => 2,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-30 05:00:00',
                'updated_at' => '2024-10-30 05:00:00',
            ],
            [
                'id' => 21,
                'nama_ruangan' => 'Multifunction Room',
                'lantai' => 3,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-25 02:00:00',
                'updated_at' => '2024-10-25 02:00:00',
            ],
            [
                'id' => 22,
                'nama_ruangan' => 'Open Public Space Utara 2',
                'lantai' => 3,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-28 04:00:00',
                'updated_at' => '2024-10-28 04:00:00',
            ],
            [
                'id' => 23,
                'nama_ruangan' => 'Ruang Meeting',
                'lantai' => 3,
                'waktu_mulai' => NULL,
                'waktu_selesai' => NULL,
                'status' => 'Check-out',
                'created_at' => '2024-10-26 03:30:00',
                'updated_at' => '2024-10-26 03:30:00',
            ],
            [
                'id' => 24,
                'nama_ruangan' => 'Open Public Space Barat',
                'lantai' => 3,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-29 03:00:00',
                'updated_at' => '2024-10-29 03:00:00',
            ],
            [
                'id' => 25,
                'nama_ruangan' => 'Ruang Kelas',
                'lantai' => 3,
                'waktu_mulai' => '00:00:00',
                'waktu_selesai' => '00:00:00',
                'status' => 'Check-out',
                'created_at' => '2024-10-30 05:00:00',
                'updated_at' => '2024-10-30 05:00:00',
            ],
        ]);
    }
}
