<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RuanganSeeder extends Seeder
{
    public function run()
    {
        DB::table('ruangan')->insert([
            [
                'id' => 1,
                'nama_ruangan' => 'Stage Outdoor',
                'kapasitas' => 100,
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Area Miniatur Candi Badut. Dapat digunakan untuk K...',
                'pic' => 'Contact Marketing',
                'lantai' => 1,
                'fasilitas' => 'Hanya Area',
                'gambar' => 'image/bBnVPrs8UEM511VGkpxJo8rvlI7R8wy8z2FK4C86.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-21 23:02:43',
            ],
            [
                'id' => 2,
                'nama_ruangan' => 'Teras Tengah',
                'kapasitas' => '50-100',
                'ukuran' => '3x6 m',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Teras Tengah. Dapat digunakan untuk berbagai aktiv...',
                'pic' => 'Div Kerjasama MCC',
                'lantai' => 2,
                'fasilitas' => 'Hanya Area',
                'gambar' => 'image/gX29j3SJKfK2O8HVVdwDo0YmltEF0w741ngoXHWw.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-21 23:29:53',
            ],
            [
                'id' => 3,
                'nama_ruangan' => 'Teras Utara',
                'kapasitas' => 50,
                'ukuran' => '7,2 x 5,4',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Area terbuka di dekat Tangga Darurat. Dapat diguna...',
                'pic' => 'Contact Marketing',
                'lantai' => 2,
                'fasilitas' => 'Hanya Area',
                'gambar' => 'image/kbdt0hIGkAON28KRRs8XUIMqpmTfv2w6yUnH7kzi.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-10-10 01:20:55',
            ],
            [
                'id' => 4,
                'nama_ruangan' => 'Coworking Space 1',
                'kapasitas' => 6,
                'ukuran' => '8,3 x 3,1',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan tertutup dilengkapi dengan bean bag, mini ...',
                'pic' => 'Contact Marketing',
                'lantai' => 4,
                'fasilitas' => null,
                'gambar' => 'image/5MltZu7mtgiBC8e8TTxfxP5TRF70o6Dyj8GDQiU2.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:35:58',
            ],
            [
                'id' => 5,
                'nama_ruangan' => 'Studio Musik & Recording',
                'kapasitas' => 8,
                'ukuran' => '3,1 x 8,3',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Studio Musik dilengkapi dengan alat musik dan reco...',
                'pic' => 'Contact Marketing',
                'lantai' => 4,
                'fasilitas' => null,
                'gambar' => 'image/gzHhvnXs02uSnfAnYNKh48kbuQOfR9xr5sxE6rk9.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:36:22',
            ],
            [
                'id' => 6,
                'nama_ruangan' => 'Workshop Seni',
                'kapasitas' => 30,
                'ukuran' => '16,2 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Area Display Instalasi Seni yang dilengkapi dengan...',
                'pic' => 'Contact Marketing',
                'lantai' => 4,
                'fasilitas' => null,
                'gambar' => 'image/ZcBugXpxNgjBPNjusvlrMZRzzFsLniO4SWZc54mF.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:39:39',
            ],
            [
                'id' => 7,
                'nama_ruangan' => 'Lab Komputer',
                'kapasitas' => 16,
                'ukuran' => '23 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan yang dilengkapi dengan komputer. Dapat dig...',
                'pic' => 'Contact Marketing',
                'lantai' => 4,
                'fasilitas' => null,
                'gambar' => 'image/PRtbxZM8pjOEre8FvXcMlCQgLpR4dVXRzJ3zqCdX.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:40:02',
            ],
            [
                'id' => 8,
                'nama_ruangan' => 'Open Public Space Utara',
                'kapasitas' => '-10',
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Area terbuka di dekat Tangga Darurat. Dapat diguna...',
                'pic' => 'Contact Marketing',
                'lantai' => 4,
                'fasilitas' => null,
                'gambar' => 'image/9qeGPr5IKDCFfVF7HJFM5vfdHlVmxkVRUnEiCfEl.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:40:22',
            ],
            [
                'id' => 9,
                'nama_ruangan' => 'Coworking Space 1',
                'kapasitas' => 10,
                'ukuran' => '3,1 x 8,3',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan tertutup untuk keperluan meeting, daily wo...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/jZs7Kas9FuQ66DTwEmEAmbVxyOsoo1NfBY2TGU7l.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:43:27',
            ],
            [
                'id' => 10,
                'nama_ruangan' => 'Coworking Space 2',
                'kapasitas' => 10,
                'ukuran' => '3,1 x 8,3',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan tertutup untuk meeting, daily working, min...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/twuKi7emPryQNgYD6jXN08nJHKSMLF2ZRrOfwnVT.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:43:51',
            ],
            [
                'id' => 11,
                'nama_ruangan' => 'Amphitheater 1',
                'kapasitas' => 150,
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan Amphitheater multifungsi. Dapat digunakan ...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/2K11yMLKJGBEJEvATHlhWBXUwlATs2EsLR4fr3w0.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:44:17',
            ],
            [
                'id' => 12,
                'nama_ruangan' => 'Amphitheater 2',
                'kapasitas' => 150,
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan Amphitheater multifungsi. Dapat digunakan ...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/f32h9LoFxhkC9V1s0Mxd1E5Bl7ISn8QV8336BLZk.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:44:42',
            ],
            [
                'id' => 13,
                'nama_ruangan' => 'Studio Foto',
                'kapasitas' => 20,
                'ukuran' => '12,2 x 7,4',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Studio Foto. Dilengkapi dengan kursi dan sofa sert...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/2a9mC6OYXXp38Ll4TbNZUiCqPNrYm2cVBVer1ltK.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:45:36',
            ],
            [
                'id' => 14,
                'nama_ruangan' => 'Ruang Fashion',
                'kapasitas' => 20,
                'ukuran' => '12,2 x 7,4',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan tertutup dilengkapi dengan mesin jahit dan...',
                'pic' => 'Contact Marketing',
                'lantai' => 5,
                'fasilitas' => null,
                'gambar' => 'image/KuctbcfZZRfBWbFWOme7Gl3V0H71VYOhQZ45NtrS.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:45:59',
            ],
            [
                'id' => 15,
                'nama_ruangan' => 'Open Public Space Utara',
                'kapasitas' => 30,
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Space terbuka yang dapat digunakan untuk latihan D...',
                'pic' => 'Contact Marketing',
                'lantai' => 6,
                'fasilitas' => null,
                'gambar' => 'image/wzzl7ERgbbcsbLDEMEOF54OQkoINYYzDFe4GKrKr.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:46:40',
            ],
            [
                'id' => 16,
                'nama_ruangan' => 'Open Public Space Timur',
                'kapasitas' => 30,
                'ukuran' => null,
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Space terbuka yang dapat digunakan untuk latihan D...',
                'pic' => 'Contact Marketing',
                'lantai' => 6,
                'fasilitas' => null,
                'gambar' => 'image/4It1FeRRjP5g5nlCUcfhPBVYXU8t5f0tldVsYZG6.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:47:23',
            ],
            [
                'id' => 17,
                'nama_ruangan' => 'Ruang Pameran',
                'kapasitas' => 50,
                'ukuran' => '13 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan pameran untuk memamerkan karya seni atau pr...',
                'pic' => 'Contact Marketing',
                'lantai' => 6,
                'fasilitas' => null,
                'gambar' => 'image/oDUoHK40T0eGAzi1mL75D7m8g2yuh8Qjb8GscfN7.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:47:45',
            ],
            [
                'id' => 18,
                'nama_ruangan' => 'Ruang Konferensi',
                'kapasitas' => 50,
                'ukuran' => '6 x 5',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan untuk acara seminar atau konferensi. Dileng...',
                'pic' => 'Contact Marketing',
                'lantai' => 6,
                'fasilitas' => null,
                'gambar' => 'image/lz6NHLsE2VQ6NwJr0NkbSBo8g5nxlTntBz8RVhJ4.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:48:06',
            ],
            [
                'id' => 19,
                'nama_ruangan' => 'Studio Digital',
                'kapasitas' => 30,
                'ukuran' => '12 x 6',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Studio Digital dilengkapi dengan komputer untuk de...',
                'pic' => 'Contact Marketing',
                'lantai' => 7,
                'fasilitas' => null,
                'gambar' => 'image/Yykq4XB9oFOFXy3J4v6A9VZ6ETstVRUVXYcpXJXb.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:48:50',
            ],
            [
                'id' => 20,
                'nama_ruangan' => 'Pusat Kreativitas',
                'kapasitas' => 50,
                'ukuran' => '15 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Pusat Kreativitas dengan fasilitas berbagai alat d...',
                'pic' => 'Contact Marketing',
                'lantai' => 7,
                'fasilitas' => null,
                'gambar' => 'image/8aDewj35q7Jl08slnm2Cpg1a7k3IlXbJ7j1C0CoF.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:49:23',
            ],
            [
                'id' => 21,
                'nama_ruangan' => 'Ruang Tamu',
                'kapasitas' => 50,
                'ukuran' => '10 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruang Tamu yang dapat digunakan untuk berbagai keper...',
                'pic' => 'Contact Marketing',
                'lantai' => 8,
                'fasilitas' => null,
                'gambar' => 'image/hz9MBgpo2gFh50kntZW9vMNnHDVm9Jwzv4zjJll9.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:49:52',
            ],
            [
                'id' => 22,
                'nama_ruangan' => 'Pusat Kegiatan',
                'kapasitas' => 100,
                'ukuran' => '15 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Pusat Kegiatan untuk acara besar seperti pesta, pe...',
                'pic' => 'Contact Marketing',
                'lantai' => 8,
                'fasilitas' => null,
                'gambar' => 'image/X2z46VoHtq2gVjJ0U52lh14PAJ4MEw24jshtx6Ic.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:50:10',
            ],
            [
                'id' => 23,
                'nama_ruangan' => 'Ruang Serbaguna',
                'kapasitas' => 30,
                'ukuran' => '12 x 7',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruang serbaguna dengan fasilitas multimedia dan mee...',
                'pic' => 'Contact Marketing',
                'lantai' => 8,
                'fasilitas' => null,
                'gambar' => 'image/ihkYgxUuGLpTwzWRjboHL2vNJ5wOeJtlnzIpkhgS.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:50:32',
            ],
            [
                'id' => 24,
                'nama_ruangan' => 'Laboratorium Teknologi',
                'kapasitas' => 40,
                'ukuran' => '20 x 10',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Laboratorium yang dilengkapi dengan alat teknologi ...',
                'pic' => 'Contact Marketing',
                'lantai' => 9,
                'fasilitas' => null,
                'gambar' => 'image/8AcPnTrkzCl37glmnwFVr6aX3OB1PFO0noei5TRi.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:50:54',
            ],
            [
                'id' => 25,
                'nama_ruangan' => 'Ruang Rapat',
                'kapasitas' => 10,
                'ukuran' => '6 x 4',
                'biaya_sewa' => 'GRATIS',
                'detail_ruangan' => 'Ruangan rapat untuk keperluan diskusi atau present...',
                'pic' => 'Contact Marketing',
                'lantai' => 9,
                'fasilitas' => null,
                'gambar' => 'image/cWmbzS4P8ZBrPykz74hvTuxCrbwVxd4RUb9YZMQX.jpg',
                'created_at' => '2024-09-20 02:25:21',
                'updated_at' => '2024-09-22 05:51:18',
            ]
        ]);
    }
}
