<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Riri',
                'email' => 'frontoffice@example.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => '2024-11-04 23:58:11',
                'updated_at' => '2024-11-04 23:58:11',
                'role' => 'frontoffice',
            ],
            [
                'id' => 2,
                'name' => 'Frishanti Yuan Paramita',
                'email' => 'ichafyp@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvE015RFHcPgW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 3,
                'name' => 'Produksi User',
                'email' => 'produksi@example.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbol3kCIbr.UK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'produksi',
            ],
            [
                'id' => 4,
                'name' => 'IT User',
                'email' => 'it@example.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oXJ3B0P7ZJO',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'IT',
            ],
            [
                'id' => 5,
                'name' => 'Dian Likos Amelia, S.AB, M.AB',
                'email' => 'dian@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'kabid',
            ],
            [
                'id' => 6,
                'name' => 'Dr. Eko Sri Yuliadi, S.Sos., M.M',
                'email' => 'ekosy@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'kadin',
            ],
            [
                'id' => 7,
                'name' => 'Ahmad Fariduddin',
                'email' => 'duddinaf@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 8,
                'name' => 'Khayatul Izzah',
                'email' => 'izzahki@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 9,
                'name' => 'Ristia Dewi',
                'email' => 'ristiard@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 10,
                'name' => 'Aura Widi Ramadhani',
                'email' => 'aurawr@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 11,
                'name' => 'Aulia Aisyah',
                'email' => 'auliaaisyah@outlook.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 12,
                'name' => 'Khansa Aliyah Rahma',
                'email' => 'khansaaliyah1999@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 13,
                'name' => 'Taufikurrahman',
                'email' => 'taufikurrahman12@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 14,
                'name' => 'Azizah Lathifah',
                'email' => 'azizah.lathifah99@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 15,
                'name' => 'Rizky Alfiansyah',
                'email' => 'rizkialfiansyah@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 16,
                'name' => 'Siti Aisyah',
                'email' => 'sitiaisyah@outlook.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 17,
                'name' => 'Andhika Setiawan',
                'email' => 'andhika@setiawan.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 18,
                'name' => 'Farhan Aska',
                'email' => 'farhanaska@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 19,
                'name' => 'Nadya Farah',
                'email' => 'nadya.farah@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 20,
                'name' => 'Suleman Pratama',
                'email' => 'sulemanpratama@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 21,
                'name' => 'Ria Permata Sari',
                'email' => 'riapermatasari@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 22,
                'name' => 'Khusnul Khotimah',
                'email' => 'khusnulkhotimah@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 23,
                'name' => 'Zulfiqri Yogi',
                'email' => 'zulfiqriyogi@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 24,
                'name' => 'Nurhasanah Elvia',
                'email' => 'nurhasanah.elvia@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 25,
                'name' => 'Ilham Ghiffari',
                'email' => 'ilhamghiffari@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 26,
                'name' => 'Fajar Kurniawan',
                'email' => 'fajarkurniawan@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 27,
                'name' => 'Anindita Putri',
                'email' => 'anindita.putri@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 28,
                'name' => 'Vivi Yuliana',
                'email' => 'vivi.yuliana@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 29,
                'name' => 'Novi Amelia',
                'email' => 'noviamelia@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 30,
                'name' => 'Fadil Mubarok',
                'email' => 'fadil.mubarok@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 31,
                'name' => 'Cynthia Dwi Larasati',
                'email' => 'cynthia.dwi@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$irFI3Is3g9Sww3iVcK47feg05hfW78FZApusNp99RvEktpAyMh2iK',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 32,
                'name' => 'Daffa Rezky',
                'email' => 'daffarezky@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 33,
                'name' => 'Aditya Mahendra',
                'email' => 'aditya.mahendra@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 34,
                'name' => 'Nurul Izzati',
                'email' => 'nurulizzati@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 35,
                'name' => 'Rina Anggraini',
                'email' => 'rinaanggraini@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 36,
                'name' => 'Zulkifli Ibrahim',
                'email' => 'zulkifli.ibrahim@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$IUEnVvkdAK5BKwi1Fq5qKOcf/403vVOsGd4F8Af6WSWuDEvCUJKOW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 37,
                'name' => 'Indra Wijaya',
                'email' => 'indrawijaya@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$tMz/NIRXxl3sotwQAC0QyORJJPdIB0LL4XbZQ9Idfbo64j6Y0jlD1G',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 38,
                'name' => 'Yusuf Hidayat',
                'email' => 'yusufhidayat@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
            [
                'id' => 39,
                'name' => 'Tata Oktaviani',
                'email' => 'tataokta@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PlpKRg7sec/fxRZpFopBJO0OUY/ObgHbrd/ihYzxZ1oBga9eIEm9qW',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'role' => 'marketing',
            ],
        ]);
    }
}
